### ISSUE TITLE
some games have no icon & title

### ISSUE THREAD

**Issue by andot** [lifehackerhansol/NDSForwarder-DSi#1]
It's cool! I installed GBARunner2 and some NDS games, all of them are works very well. But some game have no icon & title, such as Super Mario Bros. DS (iQue Chinese Version), The Legend of Zelda: Phantom Hourglass (Chinese Translation Version).

![微信图片_20220130214858](https://user-images.githubusercontent.com/232161/151702486-507f4467-8c97-41ec-a838-77016c7add55.jpg)

**Comment by lifehackerhansol** [comment]
TLOZ: Phantom Hourglass's translation patch is entirely possible that whoever created the patch did not fix the checksums in the banner. **This is an issue with the translation patch itself, and the creator should fix this with ndstool or similar.** Commit https://github.com/lifehackerhansol/NDSForwarder-DSi/commit/990239bb8726df28a0cbe68c728cf2e310b7619e should fix it anyway as I'm now checking all CRC16s.

As for the iQue, I'm not entirely certain what is going on there, but it should also be fixed by above commit. 

A build is here:
[NDSForwarder.zip](https://github.com/lifehackerhansol/NDSForwarder-DSi/files/7973106/NDSForwarder.zip)

**Comment by lifehackerhansol** [comment]
This is now in 0.1.4.

**Comment by andot** [comment]
Thank you, 0.1.4 version works very well!
